---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-secret
  namespace: default
spec:
  encryptedData:
    password: AgBm/emlKDVcjGYvNAZUnsjzA8HResKnjgusMeL8qJG0/BWiLW6QLO8hOeIs80RQSlEa4pWF5Vr4CM40poknDTgPClhmHy6L48HVGflCik8fk6Yw+nS6LdVTwOcJ4dhUrY/cyKwed6usoCWmxD/SUPLAmv5hsAWSyMURjTbMmwXaNKuCNPIs4CMLjahMzboSpQfSlzD2GpKiuo6jFxWnANb1jlCTIBXXYVbLIkzEs+YNqFXUEdp8t4W6MzUv11PeGNLUGAawbYUOhQLdkdpWu1NiYPuul5CO6tGPSbF2th1Uf8DjzvZJCdeiAd1Ma//My7aeP3O0G+fphO53ZhUQZpCLi6rT7T1JdvT2Lz1MWOHDNd0iUARA1Es4WZcdmKK3uaWLwG1KCxZ8RVFHAcZsIuv6IyMG0G+Xv9UCQo0/cmbeHaUomReaWNW56hy7tT1Fm1ttT83cPLsNFC/zoFKFUqdnNDnPBgw6+vF3MpF+h4w4+ADZqWd4OvTrwPvxdu3i+sbCj2Z0h/Z91FBRdIsnVe0Hneox0zPDcKYD4txqVzIndWaZFa+Vsizn/5VNV+mSVzjffvvx8wDZY1NpHuq2MQVLOZjv1r0PjBPVGu0Oo/r2amzzUcLLCPpyRI8nyfc9Md96wEc4fqK1bLFpHa4T+m3MyiLAfeVIgQx+R7VUQYUvmQTYsINdN+kiDcf2jMO2KG9I92oheDeiZTB98bLm
  template:
    metadata:
      creationTimestamp: null
      name: db-secret
      namespace: default
