---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-secret
  namespace: default
spec:
  encryptedData:
    password: AgDIpFjMu8Yj9xr4JlbuD6dfbBg0VFMk+KrW3OzjmIOUkd45T/XPp8vYdP080D+P09UAQF1Gg8iDvF8EaDk1Ho8QksxikipjKf8wQyRW72QWEhdioGch2tI2DRGF4smNemFLT4uZbNlNoUFGfU6d2Ajtk7d4Qd4NzwDV5Fd3F9j2Dhy1GbEUaOh8VH6oOK+32CrLfEFOokv/SS8Gc2/Vxt8M1jt4AS489ePmsIhVAxhhLUOBZ9qA4B3LbDLCJFwJQh4v9GsGqMo96WOw0Qo6wCSLa5jj/C83s6wOCZvK0SsKKe3xlQascrH4dMEyu/Mje5xu7NGxgIUFNVni6U54Kp30TA52Z5FRwLxu8zDv9pvn6FzeI/KQiAMkrHpEF8gRBNhegflbRpPcwKGP51THPhvxSXdfKsgePoF0qlmlE/mcc7UpJnOAlE/JP+aGhvPwFJ2JJbyQqzLkJ0jzG6uvSLGmLDn7v5wM5yKQ8S06shlojJqAU04k8fuSRXDdlpCIKU3fk2ATif4+xwfcuEjs7cs1MsrsKY6j9DeUhObuhRgnwPEsqu0gaaZWMpXNxbyj2eWyTamKrc4gGwG/n3oATpHRu9HirnUpUUQSJA1cSvlmMyrudWBQ7I2l0qy7pwxJ+3nvkRJI0FeBiyzM5k58z/OOLxNfrta/ioVuetFJ6wzrA9z4JGeHpTkfUJojDs1TAKDXYYm9Ua4SkUAmInNa
  template:
    metadata:
      creationTimestamp: null
      name: db-secret
      namespace: default
